# -*- coding: utf-8 -*-
"""
Created on 2025-01-08 12:50:33
---------
@summary:
---------
@author: YHLin
"""

from feapder import Item


class TbMovieItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i tb_movie
    """

    __table_name__ = "tb_movie"

    def __init__(self, *args, **kwargs):
        # self.id = None  # id
        self.title = None  # 标题
        self.directors = None  # 导演
        self.rating = None  # 评分
        self.country = None  # 国家地区
        self.summary = None  # 简介
        self.time = None  # 时长
        self.release_date = None  # 上映日期
